# Generated by Django 4.2.17 on 2025-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0002_suppliers_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
