# Generated by Django 4.2.17 on 2025-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0004_alter_suppliers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
