# Generated by Django 4.2.17 on 2025-01-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0008_remove_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_date',
            new_name='order_date',
        ),
    ]
