# Generated by Django 4.2.17 on 2025-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0011_alter_customer_email_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
